spring:
  redis:
    host: localhost
    port: 6379
    password: jhjredis12345@
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  thymeleaf:
    cache: false
  profiles:
    active: '@profileActive@'

extraProp:
      loginTimeStr: 201705041530
logging:
    level:
      root: info
    file: /Users/haojiekang/log/design.log

customjpa:
  generateDdl: true
  database: MYSQL
  databasePlatform: org.hibernate.dialect.MySQL5Dialect
  showSql: true



