spring:
  redis:
    host: localhost
    port: 6379
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  thymeleaf:
    cache: false
  profiles:
    active: dev

extraProp:
      loginTimeStr: 201705041530
logging:
    level:
      root: info
    file: d:\\fruitday\\design.log

customjpa:
  generateDdl: true
  database: MYSQL
  databasePlatform: org.hibernate.dialect.MySQL5Dialect
  showSql: true



